### ISSUE TITLE
Send newsletter to segment must consider if newsletter active+confirmed

### ISSUE THREAD

**Issue by ckemptner** [pimcore/customer-data-framework#104]
When a newsletter is sent to a segment, it currently does not consider if the checkboxes "newsletter active" + "newsletter confirmed"are confirmed in the customer object.

**Comment by fashxp** [comment]
not so easy to solve generic

**Comment by fashxp** [comment]
now solved via additional setting in send newsletter panel ... 
select checkbox fields that need to be true for customer. 

![image](https://user-images.githubusercontent.com/8792145/63675834-fac48000-c7e9-11e9-96a4-ab09ed1c8140.png)
