### ISSUE TITLE
Errors after update to pimcore 6.x

### ISSUE THREAD

**Issue by tymon82** [pimcore/customer-data-framework#110]
Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "AbstractFrontendListener" from namespace "Pimcore\Bundle\CoreBundle\EventListener\Frontend".
Did you forget a "use" statement for another namespace? in /app/vendor/pimcore/customer-management-framework-bundle/src/EventListener/Frontend/UrlActivityTracker.php on line 8

Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "AbstractFrontendListener" from namespace "Pimcore\Bundle\CoreBundle\EventListener\Frontend".
Did you forget a "use" statement for another namespace? in /app/vendor/pimcore/customer-management-framework-bundle/src/EventListener/Frontend/UrlActivityTracker.php on line 8

Call Stack:
    3.8913   86137880   1. Symfony\Component\Debug\ErrorHandler->handleException() /app/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php:0

**Comment by tymon82** [comment]
My composer file

```
{
  "name": "pimcore/demo-ecommerce",
  "type": "project",
  "description": "E-Commerce Demo Application for Pimcore 5",
  "license": "GPL-3.0-or-later",
  "config": {
    "optimize-autoloader": true,
    "sort-packages": true
  },
  "require": {
    "php": ">=7.2",
    "coreshop/core-shop": "^2.1",
    "dachcom-digital/formbuilder": "~2.6.0",
    "dachcom-digital/i18n": "^2.0",
    "dachcom-digital/members": "~2.3.0",
    "dachcom-digital/news": "~2.0.0",
    "guzzlehttp/psr7": "^1.5",
    "hwi/oauth-bundle": "dev-master",
    "php-http/curl-client": "^2.0",
    "php-http/httplug-bundle": "^1.16",
    "pimcore/pimcore": "~6.0-dev",
    "pimcore/server-side-matomo-tracking": "^0.1",
    "pimcore/web2print-tools-bundle": "^2.4",
    "wikimedia/composer-merge-plugin": "^1.4",
    "pimcore/customer-management-framework-bundle": "dev-master"
  },
  "minimum-stability" : "dev",
  "prefer-stable" : true,
  "require-dev": {
    "cache/integration-tests": "^0.16.0",
    "codeception/codeception": "~2.4.5"
  },
  "autoload": {
    "psr-4": {
      "": ["src/"],
      "Pimcore\\Model\\DataObject\\": "var/classes/DataObject",
      "Pimcore\\Model\\Object\\": "var/classes/Object",
      "Website\\": "legacy/website/lib"
    },
    "classmap": [
      "app/AppKernel.php"
    ]
  },
  "scripts": {
    "post-create-project-cmd": "Pimcore\\Composer::postCreateProject",
    "post-install-cmd": [
      "Pimcore\\Composer::postInstall",
      "@symfony-scripts"
    ],
    "post-update-cmd": [
      "Pimcore\\Composer::postUpdate",
      "@symfony-scripts",
      "Pimcore\\Composer::executeMigrationsUp"
    ],
    "pre-package-update": [
      "Pimcore\\Composer::prePackageUpdate"
    ],
    "symfony-scripts": [
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
    ]
  },
  "extra": {
    "symfony-app-dir": "app",
    "symfony-bin-dir": "bin",
    "symfony-var-dir": "var",
    "symfony-web-dir": "web",
    "symfony-tests-dir": "tests",
    "symfony-assets-install": "relative",
    "merge-plugin": {
      "include": [
        "composer.local.json"
      ],
      "recurse": true,
      "replace": true,
      "merge-dev": true,
      "merge-extra": false,
      "merge-extra-deep": false,
      "merge-scripts": false
    }
  }
}
```

**Comment by fashxp** [comment]
are you sure that you are on latest version of cmf? 
there is no file `/src/EventListener/Frontend/UrlActivityTracker.php` ... there is only https://github.com/pimcore/customer-data-framework/blob/master/src/Event/Frontend/UrlActivityTracker.php ... and this does not contain any `AbstractFrontendListener`

**Comment by tymon82** [comment]
"pimcore/customer-management-framework-bundle": "dev-master"

**Comment by fashxp** [comment]
still, please compare your files in vendor with the files here in the repository ... the file you mentioned in your error message does not exist in the repository

**Comment by AlternateIf** [comment]
@tymon82 also check your composer.json. looks like you at least have missed removing the DistributionBundle scripts. please check [update v5 to v6](https://pimcore.com/docs/5.x/Development_Documentation/Installation_and_Upgrade/Upgrade_Notes/V5_to_V6.html)

**Comment by fashxp** [comment]
maybe [this](https://github.com/pimcore/customer-data-framework/issues/111) solves your issue  too 
please try composer update on your system.
