### ISSUE TITLE
Composer dependencies issue for Pimcore 6.x

### ISSUE THREAD

**Issue by vmalyk** [pimcore/customer-data-framework#111]
Pimcore version: 6.0.0
Customer framework: 2.0.0

Package pimcore/core-version:5.8.4 is still present in composer.lock
Issue related with required version for package "pimcore/object-merger": "~1.4" and it has dependency pimcore/core-version. New version of pimcore/object-merger was released with version 2.0.0.
So, need to change requirements for this package to "pimcore/object-merger':"~2.0"

**Comment by fashxp** [comment]
thx for the hint. 
made a new release too.
