### ISSUE TITLE
Predefined Asset Metadata

### ISSUE THREAD

**Issue by shashi-kant-singh** [pimcore/customer-data-framework#116]
Select box not allowing to enter drop down values

**Comment by shashi-kant-singh** [comment]
![Screenshot from 2019-07-23 16-12-31](https://user-images.githubusercontent.com/9530223/61706056-c3832f00-ad64-11e9-8ae4-758963bba238.png)

**Comment by fashxp** [comment]
this has nothing to do with customer management framework. please make an issue at pimcore/pimcore

**Comment by dvesh3** [comment]
@shashi-kant-singh please use **configuration** column to add dropdown values like mentioned here: https://pimcore.com/docs/5.x/Development_Documentation/Tools_and_Features/Properties.html#page_Configuration-example

**Comment by shashi-kant-singh** [comment]
Thanks Divesh
