### ISSUE TITLE
Customer duplicates: Date gets lost when merging a Field Collection

### ISSUE THREAD

**Issue by ckemptner** [pimcore/customer-data-framework#118]
Just reproduced in latest advanced demo:

a) Extend customer class with field collection which features a date field
b) Add field collection information to customer data object
c) Merge duplicate customer, merge field collection field (preview shows that data will be merged correctly)
d) Open merged customer data object. Field "Date" contains value "1970-01-19"

![image](https://user-images.githubusercontent.com/13643455/62040112-43901580-b1f9-11e9-9ef3-ccf17003bd9d.png)

**Comment by aryaantony92** [comment]
Tested the scenario and the correct date is displayed now.
