### ISSUE TITLE
Customer duplicates: "Required By" dependency does not get merged

### ISSUE THREAD

**Issue by ckemptner** [pimcore/customer-data-framework#127]
I am trying to merge 2 profiles. 
Profile 1 has not "required by" dependency at all.  
Profile 2 has lots of "required by" dependencies. 

When merging the profiles, these dependencies are part of the archived profile.

I suggest the duplicate merger should merge these dependencies as well and they should not be archived but become part of the new profile. At least it should be somehow visible in the duplicate services that there are some depencies which might get lost/archived on merging of the 2 profiles.

**Comment by fashxp** [comment]
won't fix for now, we would accept PRs for it
