### ISSUE TITLE
[BUG] SQL files are not installed

### ISSUE THREAD

**Issue by dpfahlbusch** [pimcore/customer-data-framework#132]
With a fresh installation of pimcore and the customer-data-framework I always get the following error:
```
An exception occurred while executing 'SELECT PLUGIN_CMF_COLLECT_DOCUMENT_SEGMENT_ASSIGNMENTS(?)' with params [2]: SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION pimcore.PLUGIN_CMF_COLLECT_DOCUMENT_SEGMENT_ASSIGNMENTS does not exist
```

I think the problem is, that when you install the customer-data-framework bundle, it doesn't install the SQL-files with the needed functions.

**Comment by fashxp** [comment]
hi,
can you please check if the statement here can be executed on your instance? 
https://github.com/pimcore/customer-data-framework/blob/master/src/Resources/sql/segmentAssignment/storedFunctionDocument.sql

**Comment by fashxp** [comment]
possibly related to https://github.com/pimcore/demo/issues/142

**Comment by dpfahlbusch** [comment]
Hi, thank you for your quick answer.

Yes i can execute the statement on my instance.
After i executed the statements in the sql-files (https://github.com/pimcore/customer-data-framework/tree/master/src/Resources/sql/segmentAssignment) everything works normal.

But should these files be executed on install?

**Comment by fashxp** [comment]
yes it should

**Comment by fashxp** [comment]
should be fixed with https://github.com/pimcore/pimcore/issues/5111
