### ISSUE TITLE
JsConfig templating helper throws Fatal Error in __toString() method

### ISSUE THREAD

**Issue by MHundeloh** [pimcore/customer-data-framework#141]
When running pimcore admin in debug mode the JsConfig templating helper throws a Fatal Error and a stacktrace if one tries to open the details of a customer activity:

"Fatal error: Method CustomerManagementFrameworkBundle\Templating\Helper\JsConfig::__toString() must not throw an exception, caught ErrorException: Warning: count(): Parameter must be an array or an object that implements Countable in ../vendor/pimcore/customer-management-framework-bundle/src/Resources/views/layout.html.php on line 0"

**Comment by fashxp** [comment]
fixed via #142
