### ISSUE TITLE
[SegmentAssignments] Elements where segments are assigned to are not visible in dependencies tab

### ISSUE THREAD

**Issue by fashxp** [pimcore/customer-data-framework#148]
When an object is somehow used on a doument, you can see the relation in the tab "dependencies".
If CustomerSegments are used on documents, dependencies on the CustomerSegment-object are not visible even though the respective CustomerSegment is in use.

![image](https://user-images.githubusercontent.com/8792145/72435229-e0da0880-379d-11ea-8c09-50677546cbe7.png)

**Comment by fashxp** [comment]
see https://github.com/pimcore/pimcore/issues/5593

**Comment by kingjia90** [comment]
Works fine to me, if i got the issue right

Closing as this could be outdated
![image](https://user-images.githubusercontent.com/6014195/227205936-60adcc9f-48bf-4bcb-b455-2883e72ce4f2.png)
