### ISSUE TITLE
JsConfig templating helper throws Fatal Error in __toString() method 

### ISSUE THREAD

**Issue by neha04** [pimcore/customer-data-framework#155]
After updating CMF to latest version, error is displayed on opening the customers screen , activities  ...
Error: Method CustomerManagementFrameworkBundle\Templating\Helper\JsConfig::__toString() must not throw an exception, caught Error: Call to undefined function CustomerManagementFrameworkBundle\Templating\Helper\is_countable()

![cmf](https://user-images.githubusercontent.com/21308144/74916442-e0134280-53eb-11ea-8007-90522a4c0cbe.png)

is_countable() was introduced in PHP 7.3 and the minimum requirement for pimcore is php7.2 so all the systems having php 7.2 will face this issue.

Also see #141

**Comment by dvesh3** [comment]
resolved by https://github.com/pimcore/customer-data-framework/commit/603b46da34afb25bc464ac7aaef8f229ae32adfd
