### ISSUE TITLE
Updating versions

### ISSUE THREAD

**Issue by lukasvitroleracc** [pimcore/customer-data-framework#156]
Hello,

I might have missed this in the documentation but when I update versions: e.g. from 1.14 to the current 2.5.x - are there some migration commands I can run to get changes to the class definitions or should I just import the export definitions like I did during the install many months ago?

Thanks for the help

**Comment by fashxp** [comment]
there are no migrations and I'm also not sure if there are any changes to the class definitions. 
if you are missing some, I would go for manually adapting yours. just importing the class definitions will overwrite all changes that you did in the class definitions.
