### ISSUE TITLE
[Pimcore X] Think about REST webserivce

### ISSUE THREAD

**Issue by fashxp** [pimcore/customer-data-framework#166]

**Comment by aarongerig** [comment]
This could replace it: https://github.com/w-vision/PimcoreApiPlatform

**Comment by brusch** [comment]
In 6ae7ffa4108facdfa7db16ee65ef351db5964e02 I've copied `AbstractRestController` from the core to the bundle, just that Composer etc. don't have any issues, but that needs to be fixed properly, no token auth possible at the moment (just session auth).

**Comment by fashxp** [comment]
users workspaces are not considered in CMF webservices. 
so some simple token storage should be sufficient.
