### ISSUE TITLE
[SegmentAssignment] saving object when class assignment not active throws error in console

### ISSUE THREAD

**Issue by fashxp** [pimcore/customer-data-framework#17]
TypeError: Cannot read property 'breaksInheritance' of undefined
    at klass.saveSegmentAssignments (startup.js?_dc=1:284)
    at klass.preSaveObject (startup.js?_dc=1:279)

**Comment by Kzumueller** [comment]
I couldn't reproduce this issue, 
however the saving process is now decoupled from the pimcore save button
and now happens whenever data in the assignment tab is saved.

fixed in 264180d
