### ISSUE TITLE
Move validation in preAdd method

### ISSUE THREAD

**Issue by passioneight** [pimcore/customer-data-framework#206]
Currently, the validation [happens here](https://github.com/pimcore/customer-data-framework/blob/master/src/CustomerSaveManager/DefaultCustomerSaveManager.php#L142).

This, will cause the validation to throw an exception if one relies on the save handlers to auto-set data, if it is not available.

Also note that the `preUpdate` method validates [_after_ the save handlers were applied](https://github.com/pimcore/customer-data-framework/blob/master/src/CustomerSaveManager/DefaultCustomerSaveManager.php#L194) - which is the expected behaviour.

**Comment by fashxp** [comment]
fixed with #207
