### ISSUE TITLE
0 1 Serialization of 'Doctrine\DBAL\Driver\PDO\Connection' is not allowed 

### ISSUE THREAD

**Issue by ismetsener** [pimcore/customer-data-framework#216]
ERROR WITH CREATING NEW CUSTOMER -> ACTIVITIES TAB

I have installed PIMCORE-10
I created a new Class Customer : (copy of)
https://github.com/pimcore/customer-data-framework/blob/master/install/class_source/optional/class_Customer_export.json

ERROR 1)
Serialization of 'Doctrine\DBAL\Driver\PDO\Connection' is not allowed
ExceptionLogs 2Stack Trace
Exception
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/FileProfilerStorage.php (line 175)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/FileProfilerStorage.php serialize (line 175)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/Profiler.php -> write (line 101)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ProfilerListener.php -> saveProfile (line 112)
in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php -> onKernelTerminate (line 117)
in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php -> __invoke (line 230)
in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php -> callListeners (line 59)
in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 151)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php -> dispatch (line 99)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php -> terminate (line 152)
Kernel->terminate()
in public/index.php (line 38)
Tool::setCurrentRequest(null);$response = $kernel->handle($request);$response->send();$kernel->terminate($request, $response);

ERROR 2)
Symfony\Component\VarDumper\Cloner\Data objects are immutable.
BadMethodCallException
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Cloner/Data.php (line 165)
return $this->__get($key); } public function offsetSet($key, $value) { throw new \BadMethodCallException(self::class.' objects are immutable.'); } public function offsetUnset($key) { throw new \BadMethodCallException(self::class.' objects are immutable.');
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DataCollector/EventDataCollector.php -> offsetSet (line 82)
* * @see TraceableEventDispatcher / public function setCalledListeners(array $listeners) { $this->data['called_listeners'] = $listeners; } /* * Gets the called listeners. *
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DataCollector/EventDataCollector.php -> setCalledListeners (line 65)
} public function lateCollect() { if ($this->dispatcher instanceof TraceableEventDispatcher) { $this->setCalledListeners($this->dispatcher->getCalledListeners($this->currentRequest)); $this->setNotCalledListeners($this->dispatcher->getNotCalledListeners($this->currentRequest)); $this->setOrphanedEvents($this->dispatcher->getOrphanedEvents($this->currentRequest)); } $this->data = $this->cloneVar($this->data);
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/Profiler.php -> lateCollect (line 97)
public function saveProfile(Profile $profile) { // late collect foreach ($profile->getCollectors() as $collector) { if ($collector instanceof LateDataCollectorInterface) { $collector->lateCollect(); } } if (!($ret = $this->storage->write($profile)) && null !== $this->logger) { $this->logger->warning('Unable to store the profiler information.', ['configured_storage' => \get_class($this->storage)]);
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ProfilerListener.php -> saveProfile (line 112)
} } // save profiles foreach ($this->profiles as $request) { $this->profiler->saveProfile($this->profiles[$request]); } $this->profiles = new \SplObjectStorage(); $this->parents = new \SplObjectStorage(); }
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php -> onKernelTerminate (line 117)
$this->called = true; $this->priority = $dispatcher->getListenerPriority($eventName, $this->listener); $e = $this->stopwatch->start($this->name, 'event_listener'); ($this->optimizedListener ?? $this->listener)($event, $eventName, $dispatcher); if ($e->isStarted()) { $e->stop(); }
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php -> __invoke (line 230)
foreach ($listeners as $listener) { if ($stoppable && $event->isPropagationStopped()) { break; } $listener($event, $eventName, $this); } } /** * Sorts the internal list of listeners for the given event by priority.
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php -> callListeners (line 59)
} else { $listeners = $this->getListeners($eventName); } if ($listeners) { $this->callListeners($listeners, $eventName, $event); } return $event; }
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 151)
try { $this->beforeDispatch($eventName, $event); try { $e = $this->stopwatch->start($eventName, 'section'); try { $this->dispatcher->dispatch($event, $eventName); } finally { if ($e->isStarted()) { $e->stop(); } }
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php -> dispatch (line 99)
/** * {@inheritdoc} / public function terminate(Request $request, Response $response) { $this->dispatcher->dispatch(new TerminateEvent($this, $request, $response), KernelEvents::TERMINATE); } /* * @internal /
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php -> terminate (line 116)
$response = $this->handleThrowable($exception, $request, self::MASTER_REQUEST); $response->sendHeaders(); $response->sendContent(); $this->terminate($request, $response); } /* * Handles a request to convert it to a response. *
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/DebugHandlersListener.php -> terminateWithException (line 127)
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/ErrorHandler/ErrorHandler.php :: Symfony\Component\HttpKernel\EventListener{closure} (line 607)
ErrorHandler->handleException()

**Comment by fashxp** [comment]
can you please check, if https://github.com/pimcore/customer-data-framework/pull/217 fixes the issue for you?

**Comment by fashxp** [comment]
fixed with #217
