### ISSUE TITLE
There is no extension able to load the configuration for "hwi_oauth" 

### ISSUE THREAD

**Issue by ismetsener** [pimcore/customer-data-framework#221]
I have installed   CMF bundle, everything works fine, except  "Customer Duplicates"
I do not see this in the MENU

for this I added
   - { resource: cmf.yaml }
in /opt/pimcore/config/config.yaml

I also add file cmf.yaml to:
/opt/pimcore/config/cmf.yaml

also in:
/opt/pimcore-demo/vendor/pimcore/customer-management-framework-bundle/frontend-samples/sso_client/src/AppBundle/AppBundle.php

```
class AppBundle extends Bundle implements DependentBundleInterface
{
    public static function registerDependentBundles(BundleCollection $collection)
    {
        // activate bundle for SSO oauth login/register functionality
        $collection->addBundle(HWIOAuthBundle::class);
    }
}
```

but I get error:
There is no extension able to load the configuration for "hwi_oauth" (in "/opt/pimcore/config/packages/dev/../../cmf.yaml"). Looked for namespace "hwi_oauth", found ""framework", "security", "twig", "monolog", "doctrine", "doctrine_migrations", "sensio_framework_extra", "cmf_routing", "presta_sitemap", "scheb_two_factor", "fos_js_routing", "flysystem", "debug", "web_profiler", "pimcore", "pimcore_admin", "advanced_object_search", "pimcore_customer_management_framework", "elements_process_manager", "output_data_config_toolkit", "pimcore_data_hub", "pimcore_data_importer", "pimcore_ecommerce_framework", "pimcore_payment_provider_unzer", "number_sequence_generator", "object_merger", "pimcore_perspective_editor"" in /opt/pimcore/config/packages/dev/../../cmf.yaml (which is being imported from "/opt/pimcore/config/packages/dev/../../config.yaml").

**Comment by ghost** [comment]
Hi @ismetsener  facing the same issue, can u guide what is the fix?

**Comment by aashan10** [comment]
@ismetsener 

> also in:
/opt/pimcore-demo/vendor/pimcore/customer-management-framework-bundle/frontend-samples/sso_client/src/AppBundle/AppBundle.php


You don't need to modify this file as it is just a sample for implementing your own  SSO client. This file should have nothing to do with the problem you are facing. 

> for this I added
{ resource: cmf.yaml }
in /opt/pimcore/config/config.yaml
I also add file cmf.yaml to:
/opt/pimcore/config/cmf.yaml

If you are working with pimcore 10.x, there should already be a cmf.yaml file and the `resource { cmf.yaml }` should already be present during a fresh installation if you are using `pimcore/demo`.  

About the problem itself, I was not able to reproduce the issue and I need more information. Please provide me the following details:
1. Your pimcore version
2. CMF bundle version

There are a few things that you might need to check which might potentially fix this issue.
1. If you are using `pimcore/skeleton` as your application starter, please check if the `hwi/oauth-bundle` is installed in your composer.json file
2. If you are not planning on setting up sso clients, please remove the `hwi_oauth` entry from your cmf.yaml file

**Comment by aashan10** [comment]
Also, if you have the bundle installed,  make sure to register it on `src/Kernel.php`

```php
public function registerBundlesToCollection(BundleCollection $collection)
{
          ...
        $collection->addBundle(HWIOAuthBundle::class);
}

```

**Comment by dvesh3** [comment]
Closed due to inactivity. Please feel free to come back with valid scenario. thanks!
