### ISSUE TITLE
Customer Framework Management - customer  search

### ISSUE THREAD

**Issue by ismetsener** [pimcore/customer-data-framework#222]
Hi,

When I look at the "customer"   class, I see all personal fields like firstname, lastname etc
I created a new "class"  Company, with all company fields like company name, tax id, vat nr, company address  etc etc
with a link to the   "customer"   class

Now when I go to the Customer Framework Management  I can search for customers
How can I search here also for companies  (new company class)  ?

kind regards,
Ismet

**Comment by fashxp** [comment]
please use github discussions at the main repository https://github.com/pimcore/pimcore/discussions for questions and support. thx.
