### ISSUE TITLE
[Bug]: Newsletter Sync from newsletter queue to Mailchimp not working

### ISSUE THREAD

**Issue by elements-team** [pimcore/customer-data-framework#232]
### Expected behavior

Newsletter Sync with the option ``customer-data-sync `` works fine.

Executed command: ``bin/console cmf:newsletter-sync -c``

### Actual behavior

An error is thrown:
```
[Doctrine\DBAL\Driver\PDO\Exception (42000)]                                                                                                                                                                                                  
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM plugin_cmf_newsletter_queue' at line 1
```

`Exception trace:
  at /home/pimcore/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:137
 PDO->query() at /home/pimcore/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:137
 Doctrine\DBAL\Driver\PDOConnection->doQuery() at /home/pimcore/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOQueryImplementation.php:24
 Doctrine\DBAL\Driver\PDOConnection->query() at /home/pimcore/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1308
 Doctrine\DBAL\Connection->executeQuery() at /home/pimcore/www/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php:95
 Pimcore\Db\Connection->executeQuery() at /home/pimcore/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:999
 Doctrine\DBAL\Connection->fetchAll() at /home/pimcore/www/vendor/pimcore/customer-management-framework-bundle/src/Newsletter/Queue/DefaultNewsletterQueue.php:245
 CustomerManagementFrameworkBundle\Newsletter\Queue\DefaultNewsletterQueue->processItemsFromQueue() at /home/pimcore/www/vendor/pimcore/customer-management-framework-bundle/src/Newsletter/Queue/DefaultNewsletterQueue.php:118
 CustomerManagementFrameworkBundle\Newsletter\Queue\DefaultNewsletterQueue->processQueue() at /home/pimcore/www/vendor/pimcore/customer-management-framework-bundle/src/Newsletter/Manager/DefaultNewsletterManager.php:109
 CustomerManagementFrameworkBundle\Newsletter\Manager\DefaultNewsletterManager->syncCustomers() at /home/pimcore/www/vendor/pimcore/customer-management-framework-bundle/src/Newsletter/Command/NewsletterSyncCommand.php:100
 CustomerManagementFrameworkBundle\Newsletter\Command\NewsletterSyncCommand->execute() at /home/pimcore/www/vendor/symfony/console/Command/Command.php:299
 Symfony\Component\Console\Command\Command->run() at /home/pimcore/www/vendor/symfony/console/Application.php:996
 Symfony\Component\Console\Application->doRunCommand() at /home/pimcore/www/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /home/pimcore/www/vendor/symfony/console/Application.php:295
 Symfony\Component\Console\Application->doRun() at /home/pimcore/www/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/pimcore/www/vendor/symfony/console/Application.php:167
 Symfony\Component\Console\Application->run() at /home/pimcore/www/bin/console:26`

This might be, because in https://github.com/pimcore/customer-data-framework/blob/3.x/src/Newsletter/Queue/DefaultNewsletterQueue.php#L243 are no selected columns present.

### Steps to reproduce

Run command ``bin/console cmf:newsletter-sync -c``

**Comment by dvesh3** [comment]
Fixed by https://github.com/pimcore/customer-data-framework/commit/9e694717c56f309c2904c9eb4f7258a3f94dc1b0
