### ISSUE TITLE
[Improvement]: Make input filter auto wildcard (*input*)

### ISSUE THREAD

**Issue by Yivan** [pimcore/customer-data-framework#234]
### Improvement description

Hello,

Purpose of this issue is to improve the enduser experience on the search panel for customer.
Actually, it only send exact text. To search for instance for lastname begining with, we need to add a wildcard (*) at the end.

Exemple on the Pimcore demo :
- without * :

![image](https://user-images.githubusercontent.com/9025839/134363695-19063230-273a-45b7-810a-71eec6c6d8e5.png)

- with * :

![image](https://user-images.githubusercontent.com/9025839/134363864-4ab6c9d4-8649-4d49-8fc6-4bb7e5720a4b.png)

I think it would be better for user experience that automatic wildcard is added without the need to write it on the input. It could be added on email, lastname, firstname fields as well the search input field. For user not technical it wil be better.

If this way not possible, adding at least this * possibility of operator in the help so user know he can use this operator:

![image](https://user-images.githubusercontent.com/9025839/134364199-c5cbc4bb-6edc-4a4f-8b55-45fb3ec44f05.png)

Thanks.

**Comment by dvesh3** [comment]
Fixed by #319
