### ISSUE TITLE
[Bug]: Newsletter Template Export throws error

### ISSUE THREAD

**Issue by elements-team** [pimcore/customer-data-framework#236]
### Expected behavior

Clicking the button "Export Template to Mailchimp" within a email document works.

### Actual behavior

Clicking the button throws the following error: 
![image](https://user-images.githubusercontent.com/21100616/135218941-3eb8c29c-abb0-4a41-b50f-c7ec455b9829.png)

``Timestamp: Wed Sep 29 2021 09:00:51 GMT+0200 (Mitteleuropäische Sommerzeit)
Status: 500 | 
URL: /admin/customermanagementframework/templates/export
Method: post
Message: Service "CustomerManagementFrameworkBundle\Newsletter\ProviderHandler\Mailchimp\TemplateExporter" not found: even though it exists in the app's container, the container inside "CustomerManagementFrameworkBundle\Controller\Admin\TemplatesController" is a smaller service locator that only knows about the "Pimcore\Bundle\AdminBundle\Security\User\TokenStorageUserResolver", "Pimcore\Extension\Bundle\PimcoreBundleManager", "doctrine", "form.factory", "http_kernel", "message_bus", "messenger.default_bus", "parameter_bag", "pimcore.templating", "pimcore_admin.serializer", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "serializer", "session", "translator" and "twig" services. Try using dependency injection instead.
Trace: 
in /home/pimusr/www/vendor/symfony/dependency-injection/ServiceLocator.php:129
#0 /home/pimusr/www/vendor/symfony/contracts/Service/ServiceLocatorTrait.php(59): Symfony\Component\DependencyInjection\ServiceLocator->createNotFoundException('CustomerManagem...')
#1 /home/pimusr/www/vendor/symfony/dependency-injection/ServiceLocator.php(48): Symfony\Component\DependencyInjection\ServiceLocator->doGet('CustomerManagem...')
#2 /home/pimusr/www/vendor/symfony/dependency-injection/Argument/ServiceLocator.php(42): Symfony\Component\DependencyInjection\ServiceLocator->get('CustomerManagem...')
#3 /home/pimusr/www/vendor/symfony/framework-bundle/Controller/AbstractController.php(125): Symfony\Component\DependencyInjection\Argument\ServiceLocator->get('CustomerManagem...')
#4 /home/pimusr/www/vendor/pimcore/customer-management-framework-bundle/src/Controller/Admin/TemplatesController.php(40): Symfony\Bundle\FrameworkBundle\Controller\AbstractController->get('CustomerManagem...')
#5 /home/pimusr/www/vendor/symfony/http-kernel/HttpKernel.php(156): CustomerManagementFrameworkBundle\Controller\Admin\TemplatesController->exportAction(Object(Symfony\Component\HttpFoundation\Request))
#6 /home/pimusr/www/vendor/symfony/http-kernel/HttpKernel.php(78): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#7 /home/pimusr/www/vendor/symfony/http-kernel/Kernel.php(199): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 /home/pimusr/www/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#9 {main}``

### Steps to reproduce

Enable newsletter template export to mailchimp and try to click on the button "Export Template to Mailchimp" within a email document.

**Comment by dvesh3** [comment]
Fixed by #237
