### ISSUE TITLE
[Bug]: Extending from DefaultAbstractUserawareCustomer not possible

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/customer-data-framework#242]
### Expected behavior

When adding `CustomerManagementFrameworkBundle\Model\AbstractCustomer\DefaultAbstractUserawareCustomer` to the `Customer` class it should not kill Pimcore.

![image](https://user-images.githubusercontent.com/279826/144853350-a40323fd-62a7-40a9-ae22-b9f3180bd28a.png)

### Actual behavior

>  Fatal error: Class Pimcore\Model\DataObject\Customer contains 10 abstract methods and must therefore be declared abstract or implement the remaining methods (CustomerManagementFrameworkBundle\Model\CustomerInterface::getGender, CustomerManagementFrameworkBundle\Model\CustomerInterface::setGender, CustomerManagementFrameworkBundle\Model\CustomerInterface::getStreet, ...) in /var/www/pimcore/var/classes/DataObject/Customer.php on line 47

### Steps to reproduce

Add `CustomerManagementFrameworkBundle\Model\AbstractCustomer\DefaultAbstractUserawareCustomer` to the `Customer` class and load any object in the Pimcore admin.

**Comment by Navino16** [comment]
We have exactly the same issue ...
Parent PHP class is set to `\CustomerManagementFrameworkBundle\Model\AbstractCustomer`, missing methods are implemented in `App\Model\Customer` which extends `Pimcore\Model\Customer` and class override is configured in config.yaml

**Comment by dvesh3** [comment]
please make sure that your Customer class has required attributes when extending `DefaultAbstractUserawareCustomer`:

![image](https://user-images.githubusercontent.com/5137917/156041335-f9e8d300-4f75-4dca-8460-43b2e63a7587.png)

**Comment by Navino16** [comment]
It is explicitly said in the documentation that we are not required to have these attributes as long as you add a getter/setter for these attributes in your class:

> Note that the class does not need to contain the attributes as field definitions. You can also simply add the fields to your specific class implementation interface by adding getters. You must also enable the Generate Type Declarations options on the Customer class for the attributes to be compatible with the interface.

So the documentation is not good?

**Comment by dvesh3** [comment]
The thing is that these methods are not defined in Pimcore generated customer class and this class is not declared abstract so it throws exception. I would suggest to move the getters/setters to the trait and use that in Pimcore class.

I will update the docs accordingly.

**Comment by dvesh3** [comment]
Fixed by #268
