### ISSUE TITLE
[Bug]:  undefined method named "translate" in class DefaultActivityView

### ISSUE THREAD

**Issue by ITspirit** [pimcore/customer-data-framework#250]
### Expected behavior

Show view and translate default button Text.

### Actual behavior

Attempted to call an undefined method named "translate" of class "CustomerManagementFrameworkBundle\ActivityView\DefaultActivityView".

### Steps to reproduce

Create own Activity Class which should extend

Add function: 
`    public static function cmfGetDetailviewData(ActivityStoreEntryInterface $entry)
    {
        $attributes = $entry->getAttributes();

        /** @var ActivityViewInterface $activityView */
        $activityView = \Pimcore::getContainer()?->get('cmf.activity_view');
        $attributes['link'] = $activityView->createPimcoreElementLink(5, 'object');

        return $attributes;
    }
`

Throws an Exception in DefaultActivityView.php line 170:

`
return sprintf('<a href="javascript:%s" class="%s">%s</a>', $link, $buttonCssClass, $this->translate($buttonTranslationKey));
`

because "$this->translate" is not declared.

**Comment by dvesh3** [comment]
Fixed by #262
