### ISSUE TITLE
[Bug]: plugin_cmf_deletions table has no primary key but an insertOrUpdate

### ISSUE THREAD

**Issue by blankse** [pimcore/customer-data-framework#251]
### Expected behavior

I think there should be a primary key for id, type and entityType, right?

### Actual behavior

No primary keys

### Steps to reproduce

Execute the tests

**Comment by dvesh3** [comment]
Fixed by #252

**Comment by dvesh3** [comment]
Drop existing primary key(if exists) before creating new one.
