### ISSUE TITLE
[Bug]: Dataobject autosave task and CustomerSaveValidator

### ISSUE THREAD

**Issue by jremmurd** [pimcore/customer-data-framework#271]
### Expected behavior

Using the CustomerSaveValidator does not result in being prompted every x seconds that some fields are missing when auto-save task takes place.

### Actual behavior

Every x seconds a notification modal pops up if not all required fields have a value set.
![image](https://user-images.githubusercontent.com/9052094/156588420-1cf0754c-c200-46e8-836b-9cb891724e63.png)

### Steps to reproduce

1. Configure customer save validator with some fields. i.e.
![image](https://user-images.githubusercontent.com/9052094/156588566-cc127ce8-b348-448b-a1c7-5107b9792748.png)
2. create a customer and fill out data
3. you will be prompted during auto save if not all required fields are filled yet

**Comment by dvesh3** [comment]
we should skip the execution for auto save like https://github.com/pimcore/advanced-object-search/pull/144/files#diff-efbf33c02e8dd5630859ea48ce28eac21235ef0754086d327327e538f40f8226R39-R45

Change here https://github.com/pimcore/customer-data-framework/blob/337781ee45af8688af9a9015da5a6fc3ebf10257/src/Event/PimcoreObjectEventListener.php#L43

**Comment by dvesh3** [comment]
Fixed by #278
