### ISSUE TITLE
[Bug]: Migration fails for 3.2

### ISSUE THREAD

**Issue by jremmurd** [pimcore/customer-data-framework#273]
### Expected behavior

Migration does not result in error

### Actual behavior

Migration results in error
![image](https://user-images.githubusercontent.com/9052094/156727165-e627a4d4-c2e1-4aab-a7d0-b9e35ce747d0.png)

Reason seems to be
https://github.com/pimcore/customer-data-framework/pull/252

Maybe missed the BC?

### Steps to reproduce

Update to 3.2 having duplicates in table plugin_cmf_deletions
![image](https://user-images.githubusercontent.com/9052094/156727257-6bf9ec91-f79c-4bf4-a9b3-97bca5abedb8.png)

**Comment by dvesh3** [comment]
@jremmurd Is this a valid case having multiple entries with same id+entityType in `plugin_cmf_deletions`?

**Comment by jremmurd** [comment]
> @jremmurd Is this a valid case having multiple entries with same id+entityType in `plugin_cmf_deletions`?

@dvesh3 I don't know if it's a "valid" case, we got the error above on migrating. 

Performing the following query results in over 3000 entries - so I gues it's pretty relevant.

`select * from plugin_cmf_deletions group by id having count(id) > 1`

The `type` column is empty for all our entries as well, this may be because it's not set here https://github.com/pimcore/customer-data-framework/blob/3.x/src/CustomerSaveManager/DefaultCustomerSaveManager.php#L282

**Comment by jremmurd** [comment]
@dvesh3 any updates?

**Comment by dvesh3** [comment]
@jremmurd please see #276

**Comment by dvesh3** [comment]
Fixed by #276
