### ISSUE TITLE
[Bug]: Customer view throws error when customer class has a reverse relation field

### ISSUE THREAD

**Issue by Brainshaker95** [pimcore/customer-data-framework#282]
### Expected behavior

No error is thrown and die reverse relation field is not added to the view

### Actual behavior

An error is thrown in `vendor/pimcore/customer-management-framework-bundle/src/CustomerView/DefaultCustomerView.php:119`

"Call to undefined method `get<reverseRelationFieldName>`".

### Steps to reproduce

* Add a "Reverse Object Relation" field to the customer class
* Open the customer view
* Open a specific customer inside of the customer view

**Comment by aryaantony92** [comment]
@Brainshaker95  I have followed the given steps and didn't get the above mentioned error. Could you please check it once more ?

**Comment by aryaantony92** [comment]
I have added a reverse object field in the customer class and it's working in the customer view. 

![customer-view-reverse-object-relation](https://user-images.githubusercontent.com/97134765/169496970-8d8ef330-1e3d-4510-a444-73a7a92c179d.png)
