### ISSUE TITLE
[Bug]: Customer Export XLSX returns Excel file that can't be opened (0 Bytes)

### ISSUE THREAD

**Issue by jl54** [pimcore/customer-data-framework#286]
### Expected behavior

The downloaded Excel file is bigger than 0 Bytes / can be opened.

### Actual behavior

The downloaded Excel file is 0 Bytes and can't be opened.

The problem seems to be the following function in the CustomerManagementFrameworkBundle\CustomerList\Exporter\Xlsx  class.

```
public function getFilesize()
    {
        if (!$this->generated) {
            throw new \Exception('Export fore not generated: call generateExportFile before');
        }

        $stat = fstat($this->stream);

        return $stat['size'] ?? 0;
    }
```

This function always return 0;

As a workaround I adjusted the CustomerManagementFrameworkBundle\Controller\Admin\CustomersController::downloadFinishedExportAction function like this:

```
public function downloadFinishedExportAction(Request $request)
    {
        ...
        $content = $exporter->generateExportFile($exportData);
        $contentSize = strlen($content);

        $response = new Response();
        $response
            ->setContent($content)
            ->headers->add(
                [
                    'Content-Type' => $exporter->getMimeType(),
                    'Content-Length' => $contentSize,
                    'Content-Disposition' => sprintf('attachment; filename="%s"', $filename),
                ]
            );
        ...
    }
```

This seems to work.

### Steps to reproduce

Open demo.pimcore.com/admin.
Open the Customer Management Framework / Customers view.
At the bottom of the page click "Export XLSX".
Try to open the downloaded Excel file.

<img width="1366" alt="Bildschirmfoto 2022-05-06 um 14 22 43" src="https://user-images.githubusercontent.com/11390727/167130673-452851b3-9031-4993-b8eb-724624e66d87.png">

<img width="330" alt="Bildschirmfoto 2022-05-06 um 14 22 12" src="https://user-images.githubusercontent.com/11390727/167130573-5c06b5b5-3803-401b-ad5d-743a6c8073ba.png">

**Comment by aryaantony92** [comment]
Fixed by #289
