### ISSUE TITLE
[Bug]: DefaultSegmentBuilderExecutor throws error when total item count is 0

### ISSUE THREAD

**Issue by MercuryKojo** [pimcore/customer-data-framework#287]
### Expected behavior

terminate command if customer count is 0

### Actual behavior

if customer count is zero, page 0 is requested from knp pagintor which requires the values to be positive and non zero integers

either check `$totalPages` for zero here:
https://github.com/pimcore/customer-data-framework/blob/3.x/src/SegmentManager/SegmentBuilderExecutor/DefaultSegmentBuilderExecutor.php#L165

or check if `$startPage` is bigger 0 here:
https://github.com/pimcore/customer-data-framework/blob/3.x/src/SegmentManager/SegmentBuilderExecutor/DefaultSegmentBuilderExecutor.php#L233

### Steps to reproduce

PHP 8.1
have customer listing be 0 customers
execute cmf:build-segments command

**Comment by dvesh3** [comment]
Fixed by #295
