### ISSUE TITLE
Fix Symfony 5 deprecations

### ISSUE THREAD

**Issue by dvesh3** [pimcore/customer-data-framework#291]
### Improvement description

- [x] `CustomerObjectUserProvider` should not throw deprecated exception UsernameNotFoundException (can only be done when dropping support for Pimcore version 6.9) https://github.com/pimcore/customer-data-framework/pull/309

- [x]  `WebserviceAuthenticator` should not extend from deprecated AbstractGuardAuthenticator https://github.com/pimcore/customer-data-framework/pull/294

-

**Comment by dvesh3** [comment]
Re-opened as one task is pending.

**Comment by kingjia90** [comment]
> * [ ]  `CustomerObjectUserProvider` should not throw deprecated exception UsernameNotFoundException (can only be done when dropping support for Pimcore version 6.9)

Just a remind of this, since #308 just got merged

**Comment by kingjia90** [comment]
Fixed by #294 #309

**Comment by kingjia90** [comment]
Reopened as #309 mentions `resolves partially`, not sure if means `1 of 2` or if it needs a followup

**Comment by aryaantony92** [comment]
Fixed by #294 and #309
