### ISSUE TITLE
Update hwi/oauth-bundle dev requirement to v2.0

### ISSUE THREAD

**Issue by dvesh3** [pimcore/customer-data-framework#293]
### Improvement description

Check and update `hwi/oauth-bundle` dev requirement to v2.0

**Comment by kingjia90** [comment]
Is this issue "conflicting" with https://github.com/pimcore/customer-data-framework/issues/226 or it's for 3.2.15?

**Comment by dvesh3** [comment]
@kingjia90 The task was created for Symfony 6 preparation. Sorry, I didn't notice the old issue.
