### ISSUE TITLE
[Bug]: Pimcore X autoSave fully saves customer DataObject 

### ISSUE THREAD

**Issue by mariusgaldigital** [pimcore/customer-data-framework#300]
### Expected behavior

Pimcore X _autoSave_ request only saves version of customer DataObject with updated subset of segments

### Actual behavior

Pimcore X _autoSave_ request updates segment list and fully saves customer DataObject

### Steps to reproduce

**Reproduce**

1. Make sure to enable autoSave for DataObjects
2. Define DataObject with related segements
3. Setup SegmentBuilder, which updates segments based on data in customer DataObject
4. Change object field in customer DataObject (e.g. checkbox isActive, which adds a segment "active" to the customer DataObject
5. Wait for autoSave request to finish
6. Reload DataObject - The draft is now fully published

**Possible points of interest:** 

- PimcoreObjectEventListener: onPostUpdate (doesn't check if autoSave)
- DefaultCustomerSaveManager: postUpdate
- DefaultSegmentBuilderExecutor: buildCalculatedSegmentsOnCustomerSave / buildCalculatedSegments
- DefaultSegmentMerger: saveMergedSegments
- DefaultCustomerSaveManager: saveWithOptions (returns $customer->save() without further checks)

**Comment by aashan10** [comment]
@mariusgaldigital I checked on the 3.x and 3.3 branches and it is currently creating a separate version with the changed data. Could you please verify?

**Comment by aashan10** [comment]
@mariusgaldigital any updates on this?

**Comment by mariusgaldigital** [comment]
@aashan10  You are right, in the function `saveWithOptions` a Version will be handled. 

Unfortunately in `saveMergedSegments` the function `saveDirty` will be called only with the `$customer` parameter - therefore `disableVersions` will always be set to `true` in this process and the customer object is fully saved.

**Comment by dvesh3** [comment]
Fixed by #330
