### ISSUE TITLE
[Bug]: Can't assign Segment to Object or Document

### ISSUE THREAD

**Issue by MercuryKojo** [pimcore/customer-data-framework#304]
### Expected behavior

Assign Segment by dragging a Segment object into the Segment Tagging Section

### Actual behavior

`SegmentAssignmentController` throws an error, because `SegmentAssignerInterface` is accessed directly from the container instead of using DependencyInjection.

`Service "CustomerManagementFrameworkBundle\SegmentAssignment\SegmentAssigner\SegmentAssignerInterface" not found: even though it exists in the app's container, the container inside "CustomerManagementFrameworkBundle\Controller\Admin\SegmentAssignmentController" is a smaller service locator that only knows about the "Pimcore\Bundle\AdminBundle\Security\User\TokenStorageUserResolver", "Pimcore\Extension\Bundle\PimcoreBundleManager", "doctrine", "form.factory", "http_kernel", "message_bus", "messenger.default_bus", "parameter_bag", "pimcore.templating", "pimcore_admin.serializer", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "serializer", "session", "translator" and "twig" services. Try using dependency injection instead.`

### Steps to reproduce

Try adding a Segment to any Document or News Object in the Pimcore Demo

**Comment by kingjia90** [comment]
Fixed by #305
