### ISSUE TITLE
[Bug]: SegmentAssigner type conflict in __construct()

### ISSUE THREAD

**Issue by robertSt7** [pimcore/customer-data-framework#324]
### Expected behavior

No TypeError is thrown

### Actual behavior

CustomerManagementFrameworkBundle\SegmentAssignment\SegmentAssigner\SegmentAssigner::__construct(): Argument 4 ($db) must be of type Pimcore\Db\ConnectionInterface, Doctrine\DBAL\Connection given, called in /var/www/html/var/cache/dev/Container4gyT3Zg/getSegmentAssignerInterfaceService.php on line 23

### Steps to reproduce

- Checkout 11.x
- Login

**Comment by blankse** [comment]
@robertSt7 Should be fixed by https://github.com/pimcore/customer-data-framework/pull/320 right?

**Comment by robertSt7** [comment]
@blankse Yes you are right, thank you
