### ISSUE TITLE
[Bug]: Missing translation when failing to add new automation rule

### ISSUE THREAD

**Issue by kingjia90** [pimcore/customer-data-framework#346]
### Expected behavior

Alert not showing translation keys, probably were supposed to be referenced as `rules` instead of `target`

### Actual behavior

![image](https://user-images.githubusercontent.com/6014195/196134673-c68d8e5b-780e-424f-afe1-c7b93996b6da.png)

### Steps to reproduce

Just somehow break the ajax `admin/customermanagementframework/rules/add` call when creating an automation rule.
I've encountered this missing translation when verifying this https://github.com/pimcore/customer-data-framework/pull/345

**Comment by dvesh3** [comment]
Fixed by #354
