### ISSUE TITLE
[Bug]: Fix segment assignement on Object/Document

### ISSUE THREAD

**Issue by MercuryKojo** [pimcore/customer-data-framework#363]
### Expected behavior

can assign segments to objects and documents in symfony 5.4.15

### Actual behavior

throws error when assigning objects and documents

this pull request got lost from 3.2 to 3.3:
https://github.com/pimcore/customer-data-framework/pull/305

### Steps to reproduce

assign segments to objects and documents in symfony 5.4.15

**Comment by kingjia90** [comment]
Confirming that there are some missing commits 
[Compare 3.3 with 3.1.14](https://github.com/pimcore/customer-data-framework/compare/3.3...v3.2.14)

[3.2.14](https://github.com/pimcore/customer-data-framework/releases/tag/v3.2.14) was released on 20th July, by looking at the commit history and the `merge 3.2 into 3.x` was somehow not there/done and is missing from all the current branches
![image](https://user-images.githubusercontent.com/6014195/201754751-15655cb6-26b5-4a01-b031-4880e72f0c7c.png)

**Comment by dvesh3** [comment]
Cherry picked missing commits on 3.3 branch https://github.com/pimcore/customer-data-framework/commit/57d34050edc523923605281316114d2de7d9b5bb https://github.com/pimcore/customer-data-framework/commit/1c0ff33f0be8fe3288cdd533d9fd821a1ce19be0

**Comment by MercuryKojo** [comment]
@dvesh3 thank you for the quick fix.
do you have an ETA for 3.3.6?

**Comment by dvesh3** [comment]
@MercuryKojo we will tag the release next Wednesday, Nov 23rd. I have updated the due date in milestone as well.

**Comment by MercuryKojo** [comment]
@dvesh3 still no tag?
