### ISSUE TITLE
[Task] Verfiy identifyer quoting for formerly automatically quoted db calls

### ISSUE THREAD

**Issue by fashxp** [pimcore/customer-data-framework#370]
### Improvement description

related to https://github.com/pimcore/pimcore/issues/13392

check for 
- `->update(`
- `->insert(`

**Comment by kingjia90** [comment]
HIDDEN reason: this doesn't seem related to this change of `db->update()` and `db->insert()` but it's a raw sql input error in SELECT

![image](https://user-images.githubusercontent.com/6014195/215471894-ce59a08e-0b8f-4b70-826f-ec464bd80171.png)
```
#3 /var/www/html/vendor/doctrine/dbal/src/Connection.php(585): Doctrine\DBAL\Connection->executeQuery('SELECT COUNT(*)...', Array, Array)
#4 /var/www/html/dev/pimcore/pimcore/bundles/CustomReportsBundle/src/Tool/Adapter/Sql.php(38): Doctrine\DBAL\Connection->fetchOne('SELECT COUNT(*)...')
#5 /var/www/html/dev/pimcore/pimcore/bundles/CustomReportsBundle/src/Controller/Reports/CustomReportController.php(343): Pimcore\Bundle\CustomReportsBundle\Tool\Adapter\Sql->getData(NULL, NULL, NULL, 0, 50, NULL, NULL)
```

it would work if i manually quote it here
![image](https://user-images.githubusercontent.com/6014195/215472309-762f050e-c35f-4b1d-95dc-e81276e9a42c.png)
