### ISSUE TITLE
Menu not showing >> settings-json 500 error & Cannot read property 'duplicatesViewEnabled' of undefined

### ISSUE THREAD

**Issue by SilberMa** [pimcore/customer-data-framework#40]
Hi,

I tried to install the framework, but after the activation and refreshing, the menu won't show up.

Instead I get a 500 error for /admin/customermanagementframework/helper/settings-json which results in more errors e.g.: TypeError: Cannot read property 'duplicatesViewEnabled' of undefined

Did I miss something here?

**Comment by SilberMa** [comment]
Solution: 
The documentation isn't correct. 
The menu will be shown **AFTER** you created the customer class with all the fields and the errors disappear.

**Comment by dpfaffenbauer** [comment]
IMHO: the issue should be addressed anyway. It is confusing and will lead to more opened issues.
