### ISSUE TITLE
[Bug]: Mailchimp Webhook Controller can't load NewsletterManagerInterface from container

### ISSUE THREAD

**Issue by MercuryKojo** [pimcore/customer-data-framework#420]
### Expected behavior

Mailchimp webhooks should be handled via webhook controller

### Actual behavior

Webhook Controller throws error:

Service "CustomerManagementFrameworkBundle\Newsletter\Manager\NewsletterManagerInterface" not found: even though it exists in the app's container, the container inside "CustomerManagementFrameworkBundle\Controller\Rest\Mailchimp\WebhookController" is a smaller service locator that only knows about the "Pimcore\Bundle\AdminBundle\Security\User\TokenStorageUserResolver", "Pimcore\Extension\Bundle\PimcoreBundleManager", "doctrine", "form.factory", "http_kernel", "message_bus", "messenger.default_bus", "parameter_bag", "pimcore.templating", "pimcore_admin.serializer", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "serializer", "session", "translator" and "twig" services. Try using dependency injection instead.

https://github.com/pimcore/customer-data-framework/blob/3.3/src/Controller/Rest/Mailchimp/WebhookController.php#L47

### Steps to reproduce

post an example mailchimp webhook to the webhook url
Example Data:
`type=subscribe&fired_at=2023-02-21+08%3A39%3A10&data%5Bid%5D=99999999&data%5Bemail%5D=test%40gmail.com&data%5Bemail_type%5D=html&data%5Bip_opt%5D=0.0.0.0&data%5Bip_signup%5D=0.0.0.0&data%5Bweb_id%5D=999999999&data%5Bmerges%5D%5BEMAIL%5D=test%40gmail.com&data%5Bmerges%5D%5BFNAME%5D=Test&data%5Bmerges%5D%5BLNAME%5D=Test&data%5Bmerges%5D%5BCOUNTRY%5D=TE&data%5Bmerges%5D%5BSTREET%5D=Test+14&data%5Bmerges%5D%5BZIP%5D=9999&data%5Bmerges%5D%5BCITY%5D=Test&data%5Bmerges%5D%5BBIRTHDAY%5D=1999-09-19&data%5Bmerges%5D%5BSALUTATION%5D=Frau&data%5Bmerges%5D%5BINTERESTS%5D=Test&data%5Bmerges%5D%5BGROUPINGS%5D%5B0%5D%5Bid%5D=9999&data%5Bmerges%5D%5BGROUPINGS%5D%5B0%5D%5Bunique_id%5D=99999&data%5Bmerges%5D%5BGROUPINGS%5D%5B0%5D%5Bname%5D=interests&data%5Bmerges%5D%5BGROUPINGS%5D%5B0%5D%5Bgroups%5D=Test&data%5Blist_id%5D=99999999
`

**Comment by kingjia90** [comment]
Could you please if https://github.com/pimcore/customer-data-framework/pull/433 solves the problem?
I wasn't able to fully setup the mailchimp etc.. but looking at the described error, it seems that it would fixed by that.

**Comment by kingjia90** [comment]
Fixed by #433
