### ISSUE TITLE
[Bug]: Update an non-existing filter should not work. 

### ISSUE THREAD

**Issue by martineiber** [pimcore/customer-data-framework#436]
### Expected behavior

Update a non-existing filter should not throw an exception. 

### Actual behavior

An exception occurs when trying to update a filter that does not exist. 

### Steps to reproduce

Go to customers, clear all Filters and create a new filter and click on "Update existing Filter"
<img width="842" alt="image" src="https://user-images.githubusercontent.com/11687066/226580213-c058d402-e641-4d25-877d-72b5880a5c57.png">

**Comment by martineiber** [comment]
Bug also occurs in 3.3

**Comment by mattamon** [comment]
Fixed by #437
