### ISSUE TITLE
[Bug]: Customer View does not work properly

### ISSUE THREAD

**Issue by mattamon** [pimcore/customer-data-framework#457]
### Expected behavior

Open the Customer View you should be able to filter, open customers e.g.

### Actual behavior

Filter does not work.
Open up customers does not work a.m.m.

Following error occurs in the console:
caught ReferenceError: _config is not defined
    at cmf.js:1:12

### Steps to reproduce

Open op the customer view

**Comment by aryaantony92** [comment]
Will be fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/58 and https://github.com/pimcore/pimcore/pull/15067
