### ISSUE TITLE
[Bug]: Unable to create new customer

### ISSUE THREAD

**Issue by eraush** [pimcore/customer-data-framework#458]
### Expected behavior

Customer entry page should be opened

### Actual behavior

Customer entry page is not opened

### Steps to reproduce

1. Login with admin user
2. Navigate to `Customer Management Framework > Customers`
3. Click New Customer button

**Comment by aryaantony92** [comment]
This should be fixed by https://github.com/pimcore/admin-ui-classic-bundle/pull/58 and https://github.com/pimcore/pimcore/pull/15067
