### ISSUE TITLE
[Bug]: Empty dropdown option for gender list

### ISSUE THREAD

**Issue by eraush** [pimcore/customer-data-framework#461]
### Expected behavior

No empty space is displayed

Notes: it's also good to align it to capital letters (Female, Male, Others)

### Actual behavior

Empty dropdown option for gender is shown

### Steps to reproduce

1. Login with admin user
2. Navigate to `Customer Management Framework > Customers`
3. Click New Customer button
4. Click on Gender dropdown menu

<img width="884" alt="empty dropdown" src="https://user-images.githubusercontent.com/131660776/236171075-3fe43f43-9280-4d02-93c2-bef92a0268ec.png">

**Comment by aryaantony92** [comment]
Add a key to the empty space option in the gender field like "Unknown", don't allow gender field to be marked as mandatory and update the documentation

**Comment by dvesh3** [comment]
Fixed by pimcore/pimcore#15385
