### ISSUE TITLE
[Bug]:  Unable to search for duplicated customers

### ISSUE THREAD

**Issue by eraush** [pimcore/customer-data-framework#470]
### Expected behavior

Search Result displays the customers with the requested name

### Actual behavior

500 Internal Server Error is displayed

### Steps to reproduce

**Preconditions:**
Customer duplicate was created

**Steps to reproduce:**

1. Login with admin user
2. Navigate to `Customer Management Framework > Customer Duplicates`
3. Enter name of the duplicated customer into Search field
4. Press Enter button

https://github.com/pimcore/customer-data-framework/assets/131660776/8de89d7b-4438-4275-a9e5-e17f41ae788f

**Comment by dvesh3** [comment]
Fixed by #475
