### ISSUE TITLE
[Bug]: Merge duplicated customers doesn't work

### ISSUE THREAD

**Issue by eraush** [pimcore/customer-data-framework#474]
### Expected behavior

Customers are merged and removed from the Current tab
Counter of duplicated customers is decreased by one

### Actual behavior

`Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-qu+vQP5Gd85Mqj0N6eO3v1MFLxgdb71h' 'unsafe-inline' 'unsafe-eval' https://buttons.github.io/buttons.js". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.`

https://github.com/pimcore/customer-data-framework/assets/131660776/d73f3831-7fef-4686-9c31-6193c55b45c5

### Steps to reproduce

**Steps to reproduce:**

1. Login with admin user
2. Navigate to `Customer Management Framework > Customer Duplicates`
3. Click Merge button

**Comment by dvesh3** [comment]
Fixed by #477
