### ISSUE TITLE
[Bug]: Webservice Configuration View Error: Cannot use object of type Symfony\Component\HttpFoundation\JsonResponse as array

### ISSUE THREAD

**Issue by lp741** [pimcore/customer-data-framework#488]
### Expected behavior

When I try to generate webservice key from Admin I expected a key has been generated and saved

### Actual behavior

When I try to generate webservice key from Admin I received following error

Timestamp: Thu Jul 20 2023 18:31:14 GMT+0200 (Central European Summer Time)
Status: 500 | Internal Server Error
URL: /admin/customermanagementframework/settings/webservice-users?xaction=update&_dc=1689870673556
Method: POST
Message: Cannot use object of type Symfony\Component\HttpFoundation\JsonResponse as array
Trace: 
in /var/www/html/vendor/pimcore/customer-management-framework-bundle/src/Controller/Admin/SettingsController.php:51
#0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(166): CustomerManagementFrameworkBundle\Controller\Admin\SettingsController->userManagementAction(Object(Symfony\Component\HttpFoundation\Request), Object(Pimcore\Bundle\AdminBundle\Security\CsrfProtectionHandler))
#1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#2 /var/www/html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#3 /var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 /var/www/html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#5 /var/www/html/public/index.php(19): require_once('/var/www/html/v...')
#6 {main}

I solved forcing content decoding doble time at line 49 of Controller\Admin\SettingsController.php

`$data = $this->decodeJson($this->decodeJson($data->getContent(), true), true);`

```php
        if ($request->get('data')) {
            if ($request->get('xaction') == 'update') {
                $csrfProtectionHandler->checkCsrfToken($request);
                $data = $this->jsonResponse($request->get('data'));

                // PATCH solving Cannot use object of type Symfony\Component\HttpFoundation\JsonResponse as array
                $data = $this->decodeJson($this->decodeJson($data->getContent(), true), true);

                $apiKeys[$data['id']] = $data['apiKey'];
                SettingsStore::set(WebserviceAuthenticator::SETTINGS_STORE_KEY, json_encode($apiKeys), 'string', WebserviceAuthenticator::SETTINGS_STORE_SCOPE);

                return $this->jsonResponse(['data' => [], 'success' => true]);
            }
        } else {
```

### Steps to reproduce

Open admin -> Customers Menu -> Webservice Configuration View -> ⚡️

**Comment by blankse** [comment]
@lp741 I created a PR https://github.com/pimcore/customer-data-framework/pull/489

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/customer-data-framework/pull/489
