### ISSUE TITLE
[Bug]: Memory exhaustion when recreating duplicates-index

### ISSUE THREAD

**Issue by natted** [pimcore/customer-data-framework#511]
### Expected behavior

command `bin/console cmf:duplicates-index -r` will recreate the customer duplicates index successfully

### Actual behavior

When executing `bin/console cmf:duplicates-index -r` with a large amount of Customers that have many potential duplicates, `recreateIndex` within `/src/DuplicatesIndex/DefaultMariaDbDuplicatesIndex.php` fails due to memory exhaustion (before reindexing is completed).

### Steps to reproduce

Import large number of Customers, with large amount of potential duplicates. 
Run command `bin/console cmf:duplicates-index -r`

**Comment by kingjia90** [comment]
Fixed by #512
