### ISSUE TITLE
[Bug]: Can't create new Customer data objects after enabling newsletter functionality

### ISSUE THREAD

**Issue by keifphos** [pimcore/customer-data-framework#517]
### Expected behavior

After configuring newsletter syncing for MailChimp, Customer objects should still be creatable in Pimcore.

### Actual behavior

After configuring newsletter syncing for MailChimp, and upon creation of a new Customer object, an error is thrown by the `preAdd` function of the `DefaultCustomerSaveManager`.  

Specifically the `rememberOriginalCustomer` function as configuring `newsLetterSyncEnabled: true` always sets `newsletterQueueEnabled` to true, in turn always overriding the `$originalCustomerNeeded` flag as true which then fails a call to `customerProvider->getById()` as `$customer->getId()` is found as null.

### Steps to reproduce

Wth the latest version 4.0.5 - setup newsletter functionality and attempt to create a new Customer object in Pimcore.  
Note that the mail integration does function, when saving and publishing current customers we do receive updates in MailChimp so the settings and additional required object properties to do this seem to be correct, we just can't create new customers.  Seems like an easy enough fix with a null check so I will attempt to submit a PR for this today.

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/customer-data-framework/pull/520
