### ISSUE TITLE
CMF Funktionalitätserweiterung - Zielgruppen-Infor auf Dokument

### ISSUE THREAD

**Issue by elements-team** [pimcore/customer-data-framework#60]
Im CMF besteht die Möglichkeit für jede angelegte Zielgruppe ein separates Dokument zu erstellen, bzw. die Default-Version auf die Zielgruppe anzupassen. Wechselt der Redakteure zwischen diesen Zielgruppen-Dokumenten, sollte im Dokument übersichtlich angezeigt werden, auf welchem Zielgruppen-Dokument sich der Redakteur befindet. 

Mit der Bitte um Erweiterung wenn möglich.

Projekt KWT - Link zum Testserver: http://kleinwalsertal-2017.elements.zone/admin/

Danke und lG Markus

![2018-01-18_13-00-57](https://user-images.githubusercontent.com/21100616/35097273-ba146672-fc4f-11e7-9e4a-7081817a5765.jpg)

**Comment by fashxp** [comment]
no CMF issue, it's a pimcore issue ... see https://github.com/pimcore/pimcore/issues/2487
