### ISSUE TITLE
Include Profiling Consent

### ISSUE THREAD

**Issue by fashxp** [pimcore/customer-data-framework#79]
- Add `getProfilingConsent()` to abstract customer
- Add option to consider this setting in
   - targeting rule `assign target group`
   - targeting rule `track segment`
   - customer automation rule `add segment`
   - customer automation rule `add tracked segment`
   - customer automation rule `add target group segment`

**Comment by markus-moser** [comment]
`targeting rule track segment`
=> this is currently not relevant - the other rules are adopte
