### ISSUE TITLE
Customer with MailchimpAwareCustomerInterface

### ISSUE THREAD

**Issue by AndiKeiser** [pimcore/customer-data-framework#82]
Hi,
If the MailChimp sync feature is enabled, the Customer data object class needs to implement the MailchimpAwareCustomerInterface.

For the MailChimp sync feature you wrote that we have to implement the MailchimpAwareCustomerInterface in the Customer data object. When I do this, it throws an error: **Fatal error:  Class Pimcore\Model\DataObject\Customer cannot extend from interface ...**

Pimcore 5.2.0

**Comment by fashxp** [comment]
Hi, you cannot set an interface as an parent class in data object class definition. you have to create your own class and implement this interface, either by using [parent classes](https://pimcore.com/docs/5.x/Development_Documentation/Objects/Object_Classes/Class_Settings/Inheritance.html#page_Parent-Class-Class-Inheritance) or [overriding models](https://pimcore.com/docs/5.x/Development_Documentation/Extending_Pimcore/Overriding_Models.html)
