### ISSUE TITLE
How stable is this?

### ISSUE THREAD

**Issue by Magnum5234** [pimcore/customer-data-framework#85]
Hey, 
this seems like a nice addition to Pimcore features. Unfortunately it does not seem stable to me and I was not able to find any specifics about stability in this package.

Let me give you two examples:

-----
In Pimcore 5.3 and customer-data-framework 1.8 I was not able to create Customers (with the example class definition provided)
```
Status: 500 | Internal Server Error
URL: /admin/object/get
Message: Call to a member function getFieldDefinition() on null
```
(This happens in your demo-advanced.pimcore.org test system as well in case you are curious.)

-----

Downgrading Pimcore to 5.2.3 and customer-data-framework 1.7.4 I got it to work - at least for the most part. When trying to opening the segments tab on a customer the frontend js keeps crashing:
```
TypeError: this.fieldConfig.visibleFieldDefinitions is undefined
```
-----

So is this still in a form of beta testing and/or experimental? :)

**Comment by fashxp** [comment]
Hi, 
the CMF should be quite stable. We are using it in production. 
The provided sample class was not up-to-date though. Can you please try it with the latest change I did?

**Comment by Magnum5234** [comment]
I can confirm that the new sample class is working like a charm (tested with Pimcore 5.3 and customer-data-framework 1.8)
Thank you for your help!

**Comment by fashxp** [comment]
perfect, thx!
