### ISSUE TITLE
Configured CMF customer data object class "Customer" does not exist.

### ISSUE THREAD

**Issue by vinitchopra12** [pimcore/customer-data-framework#87]
I am trying to install this framework, but I am getting this error after clicking on Customer icon.
See this screenshot: http://puu.sh/B5FBJ/99b3888f36.png

The installation steps that I follow
step 1) composer require pimcore/customer-management-framework-bundle
step 2) composer update
step 3) Enable and Install the CustomerFrameworkBundle/ObectMerger from the Admin UI under the Extension.

Also, I am using pimcore 5.3.

Correct me if am doing something wrong here.

Thanks,

**Comment by fashxp** [comment]
you need to configure a customer class .. see https://github.com/pimcore/customer-data-framework/blob/master/doc/02_Installation.md#configure-customer-class

**Comment by vinitchopra12** [comment]
Thanks for the update.
Now, as per the documentation when I am trying to create the customer class from Admin UI its gives the error as "Fatal error: Class Pimcore\Model\DataObject\Customer contains 27 abstract methods". 
See this screenshot: http://puu.sh/B66NM/69a5950422.png

Please correct me if I am doing wrong here.

**Comment by fashxp** [comment]
you have to add all the mentioned attributes (firstname, lastname, ...) or use the provided class definition: https://github.com/pimcore/customer-data-framework/blob/master/install/class_source/optional/class_Customer_export.json

**Comment by vinitchopra12** [comment]
How can I update these attributes? After creating class the admin UI is not working it gives the same error on every page load.

**Comment by fashxp** [comment]
I just tried it on a clean Pimcore install ... didn't had any problems. 
maybe you need to delete your customer class and try it once more. the json can be imported here: 
![image](https://user-images.githubusercontent.com/8792145/43464056-5e9fc092-94da-11e8-888e-82c4768dda4e.png)

please also note, that this is a bugtracker only. for support see our forums https://talk.pimcore.org
